namespace A
{
    using System;

    public class PR
    {
        public static string A = "انتظر ... ";
        public static string R = "YAZSYS";
        public static string P = "تم تنفيذ الأمر بنجاح";
        public static string Q = "ادخل ارقام فقط";
        public static string I = "ادخل حروف وارقام انجليزية فقط";
        public static string D = "حدد السجل أولاً";
        public static string F = "هناك بعض الحقول الآساسية فارغة يجب إدخالها";
        public static string H = "هل انت متأكد؟";
        public static string T = "لا يحق لك فتح هذا العنصر، لأن المدير العام للنظام لم يسمح لك بذلك";
        public static string X = "يجب تحديد السجل المطلوب بشكل صحيح من القائمة اعلاه";
        public static string G = "حدد نوع البحث في اي حقل";
        public static string E = "ادخل القيمة/النص/ الاسم المطلوب البحث عنه";
        public static string K = "bWFpbHRvOlhYRUVYWD9TdWJqZWN0PVhYU1NYWCZCb2R5PVhYQkJYWA==";
        public static int A;
        public static bool A;
        public static bool R = false;
        public static bool P = false;
        public static string U = "92.205.29.131";
        public static bool Q;
        public static string L;
        public static string N;
        public static bool I;
        public static string V;
        public static string Y = "570 الجيل الرابع";
        public static string O = "https://yazsys.com/YAZ/UpdateYAZ-570";
        public static string B;
        public static string S;
        public static string Z = "12";
        public static string M = "Grean";
        public static bool D;
        public static string C = "Arial";
        public static bool F;
        public static string J = "FontThemes";
        public static string W;
        public static string AR = "win32_processor";
        public static string PR = "Error, Len Color And Size Fonts";
        public static string QR = "processorID";
        public static string IR = "Win32_bios";
        public static string DR = "version";
        public static int R;
        public static int P;
        public static int Q;
        public static int I = 0xf4291;
        public static bool H;
        public static bool T;
        public static bool X;
        public static bool G;
        public static int D = 0xf428f;
        public static int F = 0xf42a2;
        public static int H = 0xf4285;
        public static string FR = "Restart";
        public static bool E = false;
        public static bool K;
        public static bool U;
        public static bool L = true;
        public static bool N;
        public static string HR;
        public static string TR;
        public static string XR;
        public static bool V = false;
        public static string GR = "1100";
        public static string ER = "";
        public static string KR = "";
        public static string UR;
        public static string LR;
        public static string NR;
        public static string VR;
        public static string YR;
        public static int T;
        public static string OR;
        public static string BR;
        public static int X;
        public static bool Y;
        public static string SR;
        public static int G;
        public static bool O;
        public static string ZR;
        public static string MR;
        public static string CR;
        public static string JR;
        public static string WR;
        public static string AP;
        public static string RP;
        public static string PP;
        public static bool B;
        public static bool S;
        public static bool Z;
        public static bool M;
        public static bool C;
        public static bool J;
        public static bool W;
        public static bool AR;
        public static bool PR;
        public static bool QR;
        public static bool IR;
        public static bool DR;
        public static bool FR;
        public static bool HR;
        public static bool TR;
        public static string QP;
        public static string IP;
        public static string DP;
        public static string FP;
        public static string HP;
        public static string TP;
        public static bool XR;
        public static int E;
        public static bool GR;
        public static bool ER;
        public static string XP;
        public static bool KR;
        public static string GP;
        public static bool UR;
        public static bool LR;
        public static bool NR;
        public static bool VR;
        public static bool YR;
        public static bool OR;
        public static bool BR;
        public static bool SR;
        public static bool ZR;
        public static bool MR;
        public static bool CR;
        public static bool JR;
        public static bool WR;
        public static bool AP;
        public static bool RP;
        public static bool PP;
        public static bool QP;
        public static bool IP;
        public static bool DP;
        public static bool FP;
        public static bool HP;
        public static bool TP;
        public static bool XP;
        public static bool GP;
        public static bool EP;
        public static bool KP;
        public static bool UP;
        public static bool LP;
        public static bool NP;
        public static bool VP;
        public static bool YP;
        public static bool OP;
        public static bool BP;
        public static bool SP;
        public static bool ZP;
        public static bool MP;
        public static bool CP;
        public static bool JP;
        public static bool WP;
        public static bool AQ;
        public static bool RQ;
        public static bool PQ;
        public static bool QQ;
        public static bool IQ;
    }
}

